# Generated by Django 6.0 on 2025-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='id_number',
            new_name='identity_number',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='identity_document',
            field=models.FileField(default='cni', upload_to='seller/identity/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='identity_type',
            field=models.CharField(choices=[('cni', 'Carte Nationale d’Identité'), ('passport', 'Passeport')], default='cni', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ownership_document',
            field=models.FileField(default=None, upload_to='seller/ownership/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ownership_type',
            field=models.CharField(choices=[('titre_foncier', 'Titre foncier'), ('bail', 'Contrat de bail'), ('attestation', 'Attestation du chef')], default='titre_foncier', max_length=30),
            preserve_default=False,
        ),
    ]
