# Generated by Django 6.0 on 2026-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_email_code_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='identity_document',
            field=models.FileField(upload_to='identity_docs/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='identity_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='identity_type',
            field=models.CharField(choices=[('cni', 'Carte Nationale'), ('passport', 'Passeport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='ownership_document',
            field=models.FileField(upload_to='ownership_docs/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='ownership_type',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('mandate', 'Mandataire')], max_length=20),
        ),
    ]
