# Generated by Django 6.0 on 2026-01-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_submitted_at_sellerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Motif de refus ou remarque admin'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
